In [212]:
import numpy as np

## 1. Numpy Methods 

In [252]:
array_1 = np.arange(2,13,2).reshape(2,3)
print(np.array(list(range(2,21,2))))
print(np.array([[item for item in range(2,11,2)],[item for item in range(1,10,2)]]))
print(np.arange(2,21,2))
print(np.arange(2,21,2).reshape(2,5))
print(np.linspace(2,20,10))
print(np.full(6, 22))
print(np.random.randint(60,101, 12))
print(np.add(np.array([1,2,3]),4))
print(np.multiply(np.array([1,2,3]),4))
print(np.sqrt(np.array([4,9,16])))
print('power',np.power(np.array([1,2,3]),3))
print(array_1)
print('check',2 in array_1)
print('check ->', array_1 + array_1)
print('concatenate')
print(np.concatenate(([1,2], [1,2])))
print(np.hstack(([1,2], [1,2])))
print(np.vstack(([1,2], [1,2])))
new_arr = np.concatenate((array_1, array_1))
print(new_arr)
print(new_arr[3,2]) #1. Concatenate
print(np.hstack((array_1, array_1)))
print(np.hstack(([1,2], [1,2])))
print(np.vstack((array_1, array_1)))
print(array_1.flatten())
print(np.array_split(array_1.flatten(), 3)) #2. array_plit
array_2 = np.arange(2,13,2)
array_2[0],array_2[2] = array_2[2], array_2[0]
print(array_2)
print(np.where(array_2==8)) #3. Search
print(np.sort(array_2)) #4. Sort

[ 2  4  6  8 10 12 14 16 18 20]
[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]
[ 2  4  6  8 10 12 14 16 18 20]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
[22 22 22 22 22 22]
[79 90 91 97 84 86 84 91 84 82 85 60]
[5 6 7]
[ 4  8 12]
[2. 3. 4.]
power [ 1  8 27]
[[ 2  4  6]
 [ 8 10 12]]
check True
check -> [[ 4  8 12]
 [16 20 24]]
concatenate
[1 2 1 2]
[1 2 1 2]
[[1 2]
 [1 2]]
[[ 2  4  6]
 [ 8 10 12]
 [ 2  4  6]
 [ 8 10 12]]
12
[[ 2  4  6  2  4  6]
 [ 8 10 12  8 10 12]]
[1 2 1 2]
[[ 2  4  6]
 [ 8 10 12]
 [ 2  4  6]
 [ 8 10 12]]
[ 2  4  6  8 10 12]
[array([2, 4]), array([6, 8]), array([10, 12])]
[ 6  4  2  8 10 12]
(array([3]),)
[ 2  4  6  8 10 12]


# array attributes

In [253]:
array_1 = np.arange(2,41,2).reshape(4,5)
print(array_1)
print(array_1 + array_1)
print(array_1.dtype) #specifies type of elements in array
array_2 = array_1.astype(float)
print(array_2)
print(array_1.ndim)
print(array_1.size)
print(array_1.shape)
print(array_1.flat)
print(array_1.sum())
print(array_1.min())
print(array_1.max())
print(array_1.std())
print(array_1.mean())
print(array_1.var())
print(array_1.mean(axis=0))
print(array_1.mean(axis=1))
array_1.reshape(2,10)
print(array_1)
array_1.resize(1,20) # => array_1 = array_1.reshape(4,5)
print(array_1)
flattened = array_1.flatten()
raveled = array_1.ravel()
raveled[0] = 3
print(array_1.flatten()) # new copy
print(array_1.ravel()) # has reference
print(array_1.T)
print(array_1.copy()) # performs deep copy

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]
[[ 4  8 12 16 20]
 [24 28 32 36 40]
 [44 48 52 56 60]
 [64 68 72 76 80]]
int64
[[ 2.  4.  6.  8. 10.]
 [12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30.]
 [32. 34. 36. 38. 40.]]
2
20
(4, 5)
420
2
40
11.532562594670797
21.0
133.0
[17. 19. 21. 23. 25.]
[ 6. 16. 26. 36.]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]
[[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]]
[ 3  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
[ 3  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
[[ 3]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]
 [20]
 [22]
 [24]
 [26]
 [28]
 [30]
 [32]
 [34]
 [36]
 [38]
 [40]]
[[ 3  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]]


## 2.Calculation Methods(array) and Universal Functions(Numpy) - Index Based

In [139]:
grades = np.array([1,2,3])
grades_2 = np.array([2,4,6])
grades_3 = np.array([4,9,16])
print('multiply',grades * 3)
print('multiply',np.multiply(grades, 3)) # Universal function
print('add',grades + 4)
print('add',np.add(grades, 4)) # Universal function
print('power',np.power(grades, 2))
print('power',grades ** 2) # Universal function
print('sqrt', grades_3 ** (1/2))
print('sqrt', np.sqrt(grades_3)) # Universal funtion
print(grades + grades_2)
print(grades < grades_2) # comparison

multiply [3 6 9]
multiply [3 6 9]
add [5 6 7]
add [5 6 7]
power [1 4 9]
power [1 4 9]
sqrt [2. 3. 4.]
sqrt [2. 3. 4.]
[3 6 9]
[ True  True  True]


## Array Indexing and Slicing

In [69]:
array = np.arange(2,41,2).reshape(4,5)
print(array)
print(array[2,3])
print(array[1:4])
print(array[[1,3]])
print(array[:,[1,3]])
print(array[:,1:3])

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]
28
[[12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]
[[12 14 16 18 20]
 [32 34 36 38 40]]
[[ 4  8]
 [14 18]
 [24 28]
 [34 38]]
[[ 4  6]
 [14 16]
 [24 26]
 [34 36]]


## Iterate Array

In [111]:
array = np.arange(2,41,2).reshape(4,5)

for idx, x in np.ndenumerate(array):
    print(idx, x)

(0, 0) 2
(0, 1) 4
(0, 2) 6
(0, 3) 8
(0, 4) 10
(1, 0) 12
(1, 1) 14
(1, 2) 16
(1, 3) 18
(1, 4) 20
(2, 0) 22
(2, 1) 24
(2, 2) 26
(2, 3) 28
(2, 4) 30
(3, 0) 32
(3, 1) 34
(3, 2) 36
(3, 3) 38
(3, 4) 40
